# Generated by Django 3.2 on 2021-07-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='CollegeName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Assigned', 'Assigned'), ('Delievred', 'Delievred'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=40),
        ),
    ]
