# Generated by Django 3.2 on 2021-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210702_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feedback',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
