# Generated by Django 3.2 on 2021-07-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ProjectType',
            field=models.CharField(choices=[('Production Projects', 'Production Projects'), ('Assignments', 'Assignments'), ('Support', 'Support'), ('Others', 'Others')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=18),
        ),
    ]
