# Generated by Django 3.2 on 2021-07-04 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210704_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 18 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='developer',
            name='mobile',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 18 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
