# Generated by Django 3.2 on 2021-07-08 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210704_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='currencyCode',
            field=models.CharField(blank=True, choices=[('EURO', 'EURO'), ('USD', 'USD'), ('AUD', 'AUD'), ('SGP', 'SGP'), ('GBP', 'GBP')], max_length=15),
        ),
        migrations.AddField(
            model_name='bid',
            name='currencyCode',
            field=models.CharField(blank=True, choices=[('EURO', 'EURO'), ('USD', 'USD'), ('AUD', 'AUD'), ('SGP', 'SGP'), ('GBP', 'GBP')], max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='currencyCode',
            field=models.CharField(blank=True, choices=[('EURO', 'EURO'), ('USD', 'USD'), ('AUD', 'AUD'), ('SGP', 'SGP'), ('GBP', 'GBP')], max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='currencyCode',
            field=models.CharField(blank=True, choices=[('EURO', 'EURO'), ('USD', 'USD'), ('AUD', 'AUD'), ('SGP', 'SGP'), ('GBP', 'GBP')], max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+(country Code)99999'. Up to 18 digits allowed.", regex='^\\+1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='developer',
            name='mobile',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+(country Code)99999'. Up to 18 digits allowed.", regex='^\\+1?\\d{9,15}$')]),
        ),
    ]
