# Generated by Django 3.2 on 2021-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210708_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ProjectType',
            field=models.CharField(choices=[('Enterprise Projects', 'Enterprise Projects'), ('Academic Task', 'Academic Task'), ('Support', 'Support'), ('Others', 'Others')], default='', max_length=40),
        ),
    ]
