# Generated by Django 3.2 on 2021-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_projecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='Skills',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Android Development', 'Android Development'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Data Sceince', 'Data Science'), ('Others', 'Others')], default='', max_length=40),
        ),
    ]
