# Generated by Django 3.2 on 2021-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_developer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ProjectType',
            field=models.CharField(choices=[('Enterprise Projects', 'Enterprise Projects'), ('Academic Task', 'Academic Task'), ('Job Support', 'Job Support'), ('Others', 'Others')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='developer',
            name='Skills',
            field=models.CharField(default='', max_length=120),
        ),
    ]
