# Generated by Django 3.2 on 2021-07-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210717_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='DeveloperDeadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ClientDeadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
