# Generated by Django 3.2 on 2021-08-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210717_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ClientDiscussion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='DeveloperDiscussion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
