# Generated by Django 3.2 on 2021-08-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210806_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
